name: Development Build (Win64)

on:
  push:
    branches-ignore: [ master ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-BoomMapper-Development-Win64
          restore-keys: |
            Library-BoomMapper-Development-
            Library-BoomMapper-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          customParameters: -Development -EnableDeepProfilingSupport
          buildName: BoomMapper
          versioning: None

      - uses: actions/upload-artifact@v2
        with:
          name: BoomMapper-${{ github.sha }}-Win64
          path: build/StandaloneWindows64
          if-no-files-found: error
          retention-days: 7