name: Release Build

on:
  push:
    branches: [ master ]

jobs:
  build-win64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-BoomMapper-Win64
          restore-keys: |
            Library-BoomMapper-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          customParameters: -CompressWithLz4HC
          buildName: BoomMapper

      - uses: actions/upload-artifact@v2
        with:
          name: BoomMapper-Win64
          path: build/StandaloneWindows64
          if-no-files-found: error

  build-linux64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-BoomMapper-Linux64
          restore-keys: |
            Library-BoomMapper-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64
          customParameters: -CompressWithLz4HC
          buildName: BoomMapper

      - uses: actions/upload-artifact@v2
        with:
          name: BoomMapper-Linux64
          path: build/StandaloneLinux64
          if-no-files-found: error

  build-macos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-BoomMapper-MacOS
          restore-keys: |
            Library-BoomMapper-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          customParameters: -CompressWithLz4HC
          buildName: BoomMapper

      - uses: actions/upload-artifact@v2
        with:
          name: BoomMapper-OSX
          path: build/StandaloneOSX
          if-no-files-found: error

  release:
    needs: [build-win64, build-linux64, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Minor Version Bump
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: release-files

      - name: List Files
        run: |
          ls release-files

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag: ${{ steps.bump-semver.outputs.new_version }}
          name: BoomMapper ${{ steps.bump-semver.outputs.new_version }}
          files: |
            release-files/*/*